matrix:
  include:
  - language: c
      compiler: gcc
      script: 
        - cd src
        - make clean
        - make all
        - cd -
      before_install: sudo apt-get install libgsl-dev
  - language: python
    python: 3.8
    install:
      - pip install -r tests/requirements.txt
    script:
      - python -m pytest

notifications:
  email:
    - willprobert@gmail.com
