language: generic
dist: xenial
env: PYTHON_VERSION=3.6.2
before_install: 
  - sudo apt-get update
  - sudo apt-get install libgsl-dev
install:
  - pip install --user -r tests/requirements.txt
script:
  - python -m pytest
