matrix:
  include:
  - language: c
    compiler: gcc
    before_install: sudo apt-get install libgsl-dev
    script: 
      - cd src
      - make clean
      - make all
      - cd -
  - language: python
    python: 3.8
    install:
      - pip install -r tests/requirements.txt
    script:
      - python -m pytest

notifications:
  email:
    - willprobert@gmail.com
