language: generic
python: 3.8
before_install: sudo apt-get install libgsl-dev
install:
  - pip install -r tests/requirements.txt
script:
  - python -m pytest

notifications:
  email:
    - willprobert@gmail.com
